### ISSUE TITLE
Non Functional Requirements

### ISSUE THREAD

**Issue by railsagainstignorance** [Financial-Times/o-crossword#15]
# Non Functional Requirements

Must work well on 

* smartphones
   * Android: 5+
   * iPhone: OS: iOS 9+
* Screen sizes: iPhone5 and larger
   * Portrait and Landscape
* desktop
   * Latest browser versions (Chrome, IE, Safari)

No jitter 
* during scrolling or resizing or re-orienting - always have positive, smooth UI
* during keyboard entry

Allows for easy/smooth pinch-zoom

Allows for easy/smooth scroll in normal and zoomed states

**Comment by JakeChampion** [comment]
@railsagainstignorance @Lily2point0, do you know if these have been completed?
